config/routes.rb
Rails.application.routes.draw do
  post 'message/broadcast'

  devise_for :users
  resources :cards

  resources :games

  get 'games/index'

   root 'games#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params[:card]
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name)
    end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def broadcast
    Pusher.trigger('chat', 'user:said', message)
  end

  def message
    {
      :from => current_user.email, 
      :message => params[:message]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>NAME:</strong>
  <%= @game.name %>
</p>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<body>
	
	<div style="text-align:left"> </div>

	<img id="cluegb" src="http://1.bp.blogspot.com/_U1W7tPM1t20/S7NlQg1FskI/AAAAAAAAHIM/oV5xb4I_VpU/s1600/GameboardClue1963small.jpg" width="601" height="600" style="display:none">
	<canvas id="canvasOne" width="601" height="600"> </canvas>
  
  	<div id="communityCards"></div>

	<h3 id = "choosePlayer"> PLEASE ANNOUNCE AND CHOOSE YOUR PLAYER </h3>
	<h3 id = "player1" visibility = "hidden"> PLAYER 1 CARDS </h3>
	<h3 id = "player2" visibility = "hidden"> PLAYER 2 CARDS </h3>
	<h3 id = "player3" visibility = "hidden"> PLAYER 3 CARDS </h3>
	<h3 id = "community" visibility = "hidden"> COMMUNITY CARDS </h3>
	<h3 id = "diceRoll" visibility = "hidden"> DICE ROLL </h3>
	<h3 id = "murderTitle" visibility = "hidden"> MURDER - ANNOUNCE BEFORE CHECKING </h3>

	<h3 id = "publicChat" visibility = "hidden"> PUBLIC CHAT - ASK QUESTIONS </h3>

  <div id="chat-box"></div>

  <div id="message-area"></div>


	<h3 id = "privateChat" visibility = "hidden"> PRIVATE CHAT - ANSWER QUESTIONS </h3>

	<div id ="player"></div>

	<button class = "myButton" id="player1btn" onclick =" style.display = 'none' "> PLAYER 1 </button> 
	<button class = "myButton" id="player2btn" onclick =" style.display = 'none' "> PLAYER 2 </button>
	<button class = "myButton" id="player3btn" onclick =" style.display = 'none' "> PLAYER 3 </button>
	<button class = "myButton" id="murderButton"  onclick =" style.display = 'none' "> MURDER </button>


	<div id="murder"> </div>

	




<!-- detective corner -->

	<h3 id = "notes" visibility = "hidden"> DETECTIVE NOTES </h3>

	<table id="weapons" border="2" style="width:30%">

  		<tr><th colspan="3"><b>WEAPONS</b></th><tr>
  		<tr>
    		<td><input type="checkbox">Knife</td>
    		<td><input type="checkbox">Revolver</td>
    		<td><input type="checkbox">Candlestick</td>
  		</tr>
  		<tr>
    		<td><input type="checkbox">Leadpipe</td>
    		<td><input type="checkbox">Wrench</td>
    		<td><input type="checkbox">Rope</td>
  		</tr>

	</table>

	<table id= "suspects" border="2" style="width:30%">

  		<tr><th colspan="3"><b>SUSPECTS</b></th></tr>
  		<tr>
    		<td><input type="checkbox">Miss Scarlet</td>
    		<td><input type="checkbox">Mrs. White</td>
    		<td><input type="checkbox">Mrs. Peacock</td>
  		</tr>
  		<tr>
   			<td><input type="checkbox">Colonel Mustard</td>
    		<td><input type="checkbox">Professor Plum</td>
    		<td><input type="checkbox">Mr. Green</td>
  		</tr>

	</table>

	<table id ="rooms" border="2" style="width:30%">

 	 	<tr><th colspan="3"><b>ROOMS</b></th></tr>
  	 	<tr>
      		<td><input type="checkbox">Billiard Room</td>
      		<td><input type="checkbox">Ballroom</td>
      		<td><input type="checkbox">Kitchen</td>
  		</tr>
  		<tr>
    		<td><input type="checkbox">Conservatory</td>
    		<td><input type="checkbox">Study</td>
    		<td><input type="checkbox">Lounge</td>
  		</tr>
  		<tr>
   			<td><input type="checkbox">Dining Room</td>
    		<td><input type="checkbox">Hall</td>
    		<td><input type="checkbox">Library<br></td>
  		</tr>

	</table>

	<textarea id="notepad" rows="19" cols="30"> Write your CLUES here. </textarea>

	<%= yield %>

	<footer>
		<%= link_to 'Edit', edit_game_path(@game) %> |
		<%= link_to 'Back', games_path %>
	</footer>	


</body>

<script>

  window.addEventListener("load", windowLoadHandler, false);
  var Debugger = function() { };

  var theCanvas = document.getElementById("canvasOne");
  var context = theCanvas.getContext("2d");
  var img = document.getElementById("cluegb");

  var numPieces;
  var pieces;
  var dragIndex;
  var dragging;
  var mouseX;
  var mouseY;
  var dragHoldX;
  var dragHoldY;
  
    
  Debugger.log = function(message) {
    try {
      console.log(message);

    }
    catch (exception) {
      return;
    }
  }

  init();

</script>

<style>

.myButton {
  -moz-box-shadow:inset 0px 1px 3px 0px #91b8b3;
  -webkit-box-shadow:inset 0px 1px 3px 0px #91b8b3;
  box-shadow:inset 0px 1px 3px 0px #91b8b3;
  background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #c2a636), color-stop(1, #baba30));
  background:-moz-linear-gradient(top, #c2a636 5%, #baba30 100%);
  background:-webkit-linear-gradient(top, #c2a636 5%, #baba30 100%);
  background:-o-linear-gradient(top, #c2a636 5%, #baba30 100%);
  background:-ms-linear-gradient(top, #c2a636 5%, #baba30 100%);
  background:linear-gradient(to bottom, #c2a636 5%, #baba30 100%);
  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#c2a636', endColorstr='#baba30',GradientType=0);
  background-color:#c2a636;
  -moz-border-radius:5px;
  -webkit-border-radius:5px;
  border-radius:5px;
  border:1px solid #566963;
  display:inline-block;
  cursor:pointer;
  color:#000
  font-family: verdana;
  font-size:10.5px;
  font-weight:bold;
  padding:11px 23px;
  text-decoration:none;
  /*text-shadow:0px -1px 0px #2b665e*/
  text-shadow:0px -1px 0px #BABAA7
}

.myButton:hover {
  background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #baba30), color-stop(1, #c2a636));
  background:-moz-linear-gradient(top, #baba30 5%, #c2a636 100%);
  background:-webkit-linear-gradient(top, #baba30 5%, #c2a636 100%);
  background:-o-linear-gradient(top, #baba30 5%, #c2a636 100%);
  background:-ms-linear-gradient(top, #baba30 5%, #c2a636 100%);
  background:linear-gradient(to bottom, #baba30 5%, #c2a636 100%);
  filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#baba30', endColorstr='#c2a636',GradientType=0);
  background-color:#baba30;
}
.myButton:active {
  position:relative;
  top:1px;
}

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
  <script src="//js.pusher.com/2.2/pusher.min.js" type="text/javascript"></script>
  <title>SfsuCluedo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>

<style>

</style>
</html>

app/views/message/broadcast.html.erb
<h1>Message#broadcast</h1>
<p>Find me in app/views/message/broadcast.html.erb</p>